name: Build and Deploy targetter009.com

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run built.py to generate index.html
        run: python scripts/built.py

      - name: Commit and Push generated index.html
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Project film to index.html via built.py"
          file_pattern: "index.html"
          git_action_options: '--no-verify'
          push_options: '--force-with-lease'
